# Generated by Django 4.1.5 on 2023-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_servertokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertokens',
            name='token',
            field=models.CharField(max_length=2000),
        ),
    ]
