# Generated by Django 4.1.5 on 2023-01-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servertokens_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ism',
            new_name='name',
        ),
    ]
