# Generated by Django 4.1.5 on 2023-01-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ism_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='ism',
        ),
    ]
