# Generated by Django 4.1.5 on 2023-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Umra', 'Umra'), ('Haj', 'Haj')], max_length=128)),
                ('paket', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_place', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('eating', models.CharField(max_length=256)),
                ('distance', models.IntegerField()),
                ('room', models.IntegerField()),
                ('price_type', models.CharField(choices=[('$', '$'), ('UZS', 'UZS')], max_length=10)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='tarif')),
            ],
        ),
    ]
