# Generated by Django 4.1.5 on 2023-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=512)),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
