# Generated by Django 4.1.5 on 2023-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_alter_tarif_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='is_activa',
            field=models.BooleanField(default=True),
        ),
    ]
