# Generated by Django 4.1.5 on 2023-01-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayt', '0006_tarif_is_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifBron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Bron qilingan'), (1, "To'lov qilingan")], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sayt.tarif')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
