# Generated by Django 4.1.5 on 2023-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0008_tarif_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='paket',
            new_name='paket_en',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='language',
        ),
        migrations.AddField(
            model_name='tarif',
            name='paket_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='paket_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
