# Generated by Django 4.1.5 on 2023-01-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0010_tarif_paket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='paket_en',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='paket_ru',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='paket_uz',
        ),
    ]
