# Generated by Django 4.1.5 on 2023-02-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0001_initial'),
        ('sayt', '0011_remove_tarif_paket_en_remove_tarif_paket_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sayt.tarifbron')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payme.order')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payme.merchattransactionsmodel')),
            ],
        ),
    ]
