# Generated by Django 4.1.5 on 2023-04-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0012_paymeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymeOrder',
        ),
    ]
